version: '3.7'

services:
  app:
    image: ghcr.io/meta-metopia/chatbot:v1.0.4
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      TELEGRAM_KEY: ${TELEGRAM_KEY}
      BLOOM_API_KEY: ${BLOOM_API_KEY}
      BLOOM_ENDPOINT: ${BLOOM_ENDPOINT}
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    ports:
      - '8080:8080'